services:
  cliring:
    build: ./
    ports:
      - '8080:8080'
    command:
      - go
      - run
      - ./cmd/cliring/main.go
    environment:
      DNS: "postgres://postgres:hFAClzgcwH5QNmEja8CdzwVDMCnxxm@db:5432/cliring?sslmode=disable"
    networks:
      - cliring-network
  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: hFAClzgcwH5QNmEja8CdzwVDMCnxxm
      POSTGRES_USER: postgres
      POSTGRES_DB: cliring
    ports:
      - "5440:5432"
    networks:
      - cliring-network
networks:
  cliring-network:
    driver: bridge
